---
Name: toastfonts
---

PageController:
  extensions:
    - Toast\ThemeFonts\Extensions\PageControllerExtension

Toast\ThemeFonts\Models:
  default_fonts:
    - body: null
    - headings: null


SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Toast\ThemeFonts\Extensions\SiteConfigExtension

SilverStripe\Assets\File:
  allowed_extensions:
    - ttf
    - otf
    - woff
    - woff2
    - eot
    - svg

SilverStripe\ORM\DatabaseAdmin:
  extensions:
    - Toast\ThemeFonts\Extensions\DatabaseAdminExtension
