---
Name: toastfonts
---

Toast\ThemeFonts\Models\ThemeFontFamily:
  default_fonts:
    - body: null
    - headings: null
  available_weights:
    - 400
    - 700

PageController:
  extensions:
    - Toast\ThemeFonts\Extensions\PageControllerExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Toast\ThemeFonts\Extensions\SiteConfigExtension
  css_folder_path: '/public/assets/styles/'

SilverStripe\ORM\DatabaseAdmin:
  extensions:
    - Toast\ThemeFonts\Extensions\DatabaseAdminExtension

SilverStripe\Assets\File:
  allowed_extensions:
    - ttf
    - otf
    - woff
    - woff2
    - eot
    - svg
